### ISSUE TITLE
(Epic) Recreate every page

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#15]
## We need all our content back!
A box can be ticked when the page in question exists **with any aliases*** and has no visual or functional regression from the live version.

> * with any aliases

_example: alias-one | alias-two ==> `operationcode.org/alias-one` & `operationcode.org/alias-two`_

### The following unauthenticated pages:

(x means claimed)
- [ ] landing - [mock-up](https://invis.io/NTO3FK69UQS)
- [ ] get_involved - [mock-up](https://invis.io/GRO3FKUEZMX)
- [ ] events - [mock-up](https://invis.io/NMO3FLFWQ43)
- [x] chapter_leader ( @wimo7083 )
- [x] contact ( @JohnGoure )
- [x] branding ( @ksmacleod99 )
- [x] code_schools ( @kylemh )
- [ ] press
- [ ] challenge
- [ ] policy
- [ ] team

### The following authenticated pages:
These components will require on-the-fly refactoring as they're dependent on `react-router` (which we're not using anymore).

 [ALL BLOCKED]
- [ ] join | signup | sign-up | sign_up [BLOCKED]
- [ ] login [BLOCKED]
- [ ] social_login
- [ ] profile
- [ ] profile/verify
- [ ] scholarships
- [ ] reset_password

### FINISHED! 🎉 
- [x] about ( @PeterEckIII )
- [x] history ( @PeterEckIII )
- [x] terms ( Rich Supak )
- [x] faq ( @JohnGoure )
- [x] jobs ( @chrismgonzalez )
- [x] leadership_circle ( @chrismgonzalez )

**Comment by kylemh** [comment]
As of this moment, per @dmarchante, many new pages have been put on hold pending redesign or deletion.

List of pages available for working:
faq, branding, history

**Comment by chrismgonzalez** [comment]
I will try to get some work done on the jobs page this week.

**Comment by chrismgonzalez** [comment]
Got part of the jobs page setup.  The only thing that needs to be added is the logic behind the individual jobs being pulled in from a db.  I also added links to the nav so that we can see the history and jobs page.

**Comment by dmarchante** [comment]
https://invis.io/3CNY7XQYW94#/318818762_OC_Members_Landing_Page

**Comment by dmarchante** [comment]
https://projects.invisionapp.com/d/#/console/15336699/318818763/preview

**Comment by dmarchante** [comment]
Mock-Ups:
https://invis.io/NTO3FK69UQS - main page
https://invis.io/GRO3FKUEZMX - get involved
https://invis.io/NMO3FLFWQ43 - events

**Comment by dmarchante** [comment]
Wireframes:
https://invis.io/5DO3FMBUBCZ - main landing
https://invis.io/7WO3FMN92BA - member landing
https://invis.io/FAO3FN1ERNK - get involved
https://invis.io/RJO3FNEQNY7 - events

**Comment by kylemh** [comment]
Closed in favor of separate issues 👍
